@extends('admin.layouts.app')

@section('content')
<div class="px-4 sm:px-0">
    <div class="mb-8"><a href="{{ route('admin.public-pages.index') }}" class="text-sm text-blue-600">← 返回官网内容</a><h1 class="mt-2 text-2xl font-bold text-gray-900">公开事实与证据</h1><p class="mt-1 text-sm text-gray-600">E3 是进入正式机构页面的最低门槛；撤回或降级会立即下线受影响活动快照。</p></div>
    @if(session('message'))<div class="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('message') }}</div>@endif
    @if($errors->any())<div class="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif
    <form method="post" action="{{ route('admin.public-facts.store') }}" class="mb-6 grid gap-4 rounded-lg border border-gray-200 bg-white p-5 shadow-sm md:grid-cols-4">@csrf
        <input name="fact_code" required placeholder="事实编码，如 ORG-LICENSE-01" class="rounded-md border-gray-300 text-sm"><input name="entity_type" required placeholder="实体类型" class="rounded-md border-gray-300 text-sm"><input name="statement" required placeholder="可公开核验的事实陈述" class="rounded-md border-gray-300 text-sm md:col-span-2">
        <select name="evidence_level" class="rounded-md border-gray-300 text-sm">@for($i=0;$i<=4;$i++)<option value="{{ $i }}">E{{ $i }}</option>@endfor</select><input name="evidence_label" placeholder="证据名称" class="rounded-md border-gray-300 text-sm"><input name="evidence_url" placeholder="https:// 核验地址" class="rounded-md border-gray-300 text-sm md:col-span-2">
        <select name="visibility" class="rounded-md border-gray-300 text-sm"><option value="internal">内部</option><option value="public">公开</option><option value="restricted">受限</option></select><select name="status" class="rounded-md border-gray-300 text-sm"><option value="draft">草稿</option><option value="approved">已批准</option><option value="withdrawn">已撤回</option></select><input name="owner_name" placeholder="责任人" class="rounded-md border-gray-300 text-sm"><button class="rounded-md bg-gray-900 px-4 py-2 text-sm font-semibold text-white">新增事实草稿</button>
    </form>
    <div class="space-y-4">@forelse($facts as $fact)<form method="post" action="{{ route('admin.public-facts.update',$fact->id) }}" class="grid gap-3 rounded-lg border border-gray-200 bg-white p-5 shadow-sm md:grid-cols-6">@csrf @method('PUT')
        <div class="md:col-span-6 flex justify-between"><b class="text-gray-900">{{ $fact->fact_code }}</b><span class="text-xs text-gray-500">关联 {{ $fact->pages_count }} 个页面</span></div><input name="fact_code" value="{{ $fact->fact_code }}" required class="rounded-md border-gray-300 text-sm"><input name="entity_type" value="{{ $fact->entity_type }}" required class="rounded-md border-gray-300 text-sm"><textarea name="statement" required rows="2" class="rounded-md border-gray-300 text-sm md:col-span-4">{{ $fact->statement }}</textarea>
        <select name="evidence_level" class="rounded-md border-gray-300 text-sm">@for($i=0;$i<=4;$i++)<option value="{{ $i }}" @selected($fact->evidence_level===$i)>E{{ $i }}</option>@endfor</select><input name="evidence_label" value="{{ $fact->evidence_label }}" placeholder="证据名称" class="rounded-md border-gray-300 text-sm"><input name="evidence_url" value="{{ $fact->evidence_url }}" placeholder="核验地址" class="rounded-md border-gray-300 text-sm md:col-span-2"><select name="visibility" class="rounded-md border-gray-300 text-sm">@foreach(['public'=>'公开','internal'=>'内部','restricted'=>'受限'] as $v=>$l)<option value="{{ $v }}" @selected($fact->visibility===$v)>{{ $l }}</option>@endforeach</select><select name="status" class="rounded-md border-gray-300 text-sm">@foreach(['draft'=>'草稿','approved'=>'已批准','published'=>'已发布','withdrawn'=>'已撤回'] as $v=>$l)<option value="{{ $v }}" @selected($fact->status===$v)>{{ $l }}</option>@endforeach</select>
        <input name="owner_name" value="{{ $fact->owner_name }}" placeholder="责任人" class="rounded-md border-gray-300 text-sm"><input type="date" name="effective_at" value="{{ $fact->effective_at?->toDateString() }}" class="rounded-md border-gray-300 text-sm"><input type="date" name="expires_at" value="{{ $fact->expires_at?->toDateString() }}" class="rounded-md border-gray-300 text-sm"><button class="rounded-md bg-blue-600 px-4 py-2 text-sm font-semibold text-white">保存并使关联审核失效</button>
    </form>@empty<div class="rounded-lg border border-dashed border-gray-300 p-10 text-center text-sm text-gray-500">尚无公开事实。</div>@endforelse</div>
</div>
@endsection
