ARG NGINX_IMAGE=nginx:1.27-alpine
FROM ${NGINX_IMAGE}

WORKDIR /var/www/html

COPY public /var/www/html/public
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

RUN rm -f /var/www/html/public/storage \
    && ln -s ../storage/app/public /var/www/html/public/storage
