@extends('admin.layouts.app')

@section('content')
<div class="px-4 sm:px-0">
    <div class="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><a href="{{ route('admin.public-pages.index') }}" class="text-sm text-blue-600">← 返回官网内容</a><h1 class="mt-2 text-2xl font-bold text-gray-900">{{ $page->title }}</h1><p class="mt-1 font-mono text-xs text-gray-500">v{{ $page->version }} · {{ $page->content_hash }}</p></div>@if($page->activeSnapshot)<a href="{{ \App\Support\ZeroPoint\PublicPageUrl::for($page->slug, $page->area) }}" target="_blank" rel="noopener" class="rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-700">打开当前公开版</a>@endif</div>
    @if(session('message'))<div class="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('message') }}</div>@endif
    @if($errors->any())<div class="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
        <form method="post" action="{{ route('admin.public-pages.update', $page->id) }}" class="space-y-5 rounded-lg border border-gray-200 bg-white p-6 shadow-sm">@csrf @method('PUT')
            <div class="grid gap-4 md:grid-cols-2"><label class="text-sm font-medium text-gray-700">标题<input name="title" value="{{ old('title', $page->title) }}" required class="mt-1 w-full rounded-md border-gray-300"></label><label class="text-sm font-medium text-gray-700">眉题<input name="eyebrow" value="{{ old('eyebrow', $page->eyebrow) }}" class="mt-1 w-full rounded-md border-gray-300"></label></div>
            <label class="block text-sm font-medium text-gray-700">摘要<textarea name="summary" rows="3" class="mt-1 w-full rounded-md border-gray-300">{{ old('summary', $page->summary) }}</textarea></label>
            <label class="block text-sm font-medium text-gray-700">正文（Markdown）<textarea name="body" rows="18" required class="mt-1 w-full rounded-md border-gray-300 font-mono text-sm">{{ old('body', $page->body) }}</textarea></label>
            <div class="grid gap-4 md:grid-cols-2"><label class="text-sm font-medium text-gray-700">区域<select name="area" class="mt-1 w-full rounded-md border-gray-300">@foreach(['institution'=>'机构','health'=>'健康科普','governance'=>'治理'] as $value=>$label)<option value="{{ $value }}" @selected(old('area',$page->area)===$value)>{{ $label }}</option>@endforeach</select></label><label class="text-sm font-medium text-gray-700">页面类型<input name="page_type" value="{{ old('page_type', $page->page_type) }}" required class="mt-1 w-full rounded-md border-gray-300"></label></div>
            <div class="grid gap-4 md:grid-cols-2"><label class="text-sm font-medium text-gray-700">SEO 标题<input name="seo_title" value="{{ old('seo_title', $page->seo_title) }}" class="mt-1 w-full rounded-md border-gray-300"></label><label class="text-sm font-medium text-gray-700">Meta 描述<textarea name="meta_description" rows="2" class="mt-1 w-full rounded-md border-gray-300">{{ old('meta_description', $page->meta_description) }}</textarea></label></div>
            <div class="grid gap-4 md:grid-cols-2"><label class="text-sm font-medium text-gray-700">CTA 文案<input name="cta_label" value="{{ old('cta_label', $page->cta_label) }}" {{ $page->area === 'health' ? 'disabled' : '' }} class="mt-1 w-full rounded-md border-gray-300"></label><label class="text-sm font-medium text-gray-700">CTA 地址<input name="cta_url" value="{{ old('cta_url', $page->cta_url) }}" {{ $page->area === 'health' ? 'disabled' : '' }} class="mt-1 w-full rounded-md border-gray-300"></label></div>
            <fieldset><legend class="text-sm font-semibold text-gray-800">绑定公开事实</legend><p class="mb-2 mt-1 text-xs text-gray-500">正式机构页只能绑定 E3 及以上、公开、有效且已批准的事实。</p><div class="max-h-52 space-y-2 overflow-auto rounded-md border border-gray-200 p-3">@forelse($facts as $fact)<label class="flex items-start gap-2 text-sm"><input type="checkbox" name="fact_ids[]" value="{{ $fact->id }}" @checked($page->facts->contains($fact->id)) class="mt-1"><span><b>{{ $fact->fact_code }}</b> · E{{ $fact->evidence_level }} · {{ $fact->statement }}</span></label>@empty<p class="text-sm text-gray-500">尚无事实记录。</p>@endforelse</div></fieldset>
            <button class="rounded-md bg-blue-600 px-4 py-2 text-sm font-semibold text-white">保存草稿</button>
        </form>
        <aside class="space-y-5">
            <section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">四门审核</h2><p class="mt-1 text-xs text-gray-500">所有审核必须绑定同一个内容哈希。任何正文或事实变化都会失效。</p>@php($latest = $page->approvals->where('content_hash',$page->content_hash)->keyBy('gate'))<div class="mt-4 space-y-3">@foreach($gates as $gate)<form method="post" action="{{ route('admin.public-pages.approve', $page->id) }}" class="rounded-md border border-gray-200 p-3">@csrf<input type="hidden" name="gate" value="{{ $gate }}"><div class="flex items-center justify-between"><b class="text-sm text-gray-800">{{ $gate }}</b><span class="text-xs {{ data_get($latest->get($gate),'decision')==='approved' ? 'text-emerald-700' : 'text-gray-500' }}">{{ data_get($latest->get($gate),'decision','待审核') }}</span></div><input name="note" placeholder="审核说明" class="mt-2 w-full rounded-md border-gray-300 text-sm"><div class="mt-2 flex gap-2"><button name="decision" value="approved" class="rounded bg-emerald-600 px-3 py-1.5 text-xs font-semibold text-white">通过</button><button name="decision" value="rejected" class="rounded border border-red-200 px-3 py-1.5 text-xs font-semibold text-red-700">驳回</button></div></form>@endforeach</div>
                <form method="post" action="{{ route('admin.public-pages.publish', $page->id) }}" class="mt-4">@csrf<button class="w-full rounded-md bg-gray-900 px-4 py-2 text-sm font-semibold text-white">发布当前审核版本</button></form>
            </section>
            <section class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">发布历史</h2><div class="mt-3 space-y-3">@forelse($page->snapshots as $snapshot)<div class="rounded-md bg-gray-50 p-3 text-xs text-gray-600"><div class="flex justify-between"><b>v{{ $snapshot->version }}</b><span>{{ $snapshot->is_active ? '当前活动' : $snapshot->published_at?->format('Y-m-d H:i') }}</span></div>@unless($snapshot->is_active)<form method="post" action="{{ route('admin.public-pages.rollback', [$page->id,$snapshot->id]) }}" class="mt-2">@csrf<button class="text-blue-600">以此版本重新发布</button></form>@endunless</div>@empty<p class="text-sm text-gray-500">尚无发布快照。</p>@endforelse</div></section>
        </aside>
    </div>
</div>
@endsection
