@extends('admin.layouts.app')
@section('topbar-title','选择专题文章')
@section('content')
@include('admin.topics._style')
<div class="topic-shell space-y-5" data-topic-selector data-key="{{ $formKey }}">
 <div class="flex flex-wrap justify-between gap-3"><div><h1 class="text-2xl font-semibold">选择文章</h1><p class="topic-help mt-2">{{ $sites[$site]??$site }} · 仅展示本站可公开阅读的文章，已选文章可再次取消。</p></div><a class="topic-button topic-primary" href="{{ $returnUrl }}" data-topic-done>完成选择并返回（<span data-selected-count>0</span>）</a></div>
 <form method="GET" class="topic-panel grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><input type="hidden" name="site" value="{{ $site }}"><input type="hidden" name="form_key" value="{{ $formKey }}"><input type="hidden" name="form_token" value="{{ request('form_token') }}"><input type="hidden" name="topic" value="{{ request('topic') }}"><div><label>分类</label><select name="category_id"><option value="">全部分类</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(request('category_id')==$category->id)>{{ $category->name }}</option>@endforeach</select></div><div><label>标题搜索</label><input name="search" value="{{ request('search') }}"></div><div><label>发布自</label><input type="date" name="after" value="{{ request('after') }}"></div><div><label>发布至</label><input type="date" name="before" value="{{ request('before') }}"></div><div class="flex items-end"><button class="topic-button">筛选文章</button></div></form>
 <div class="topic-panel"><h2 class="font-semibold">已选文章</h2><div data-topic-selected class="mt-3 flex flex-wrap gap-2"></div></div>
 <div class="flex flex-wrap gap-2"><button class="topic-button" type="button" data-select-results>选择当前页结果</button><button class="topic-button" type="button" data-clear-results>取消当前页结果</button><span class="topic-help self-center" data-selector-message></span></div>
 <div class="overflow-x-auto border border-gray-200 rounded-lg bg-white"><table><thead><tr><th>选择</th><th>文章标题与摘要</th><th>来源与状态</th><th>发布时间</th></tr></thead><tbody>@forelse($articles as $article)<tr><td><input type="checkbox" data-topic-choice value="{{ $article->id }}" data-title="{{ $article->title }}" data-excerpt="{{ strip_tags($article->excerpt??'') }}" data-url="{{ $sourceOptions[$article->id]['url'] }}" data-category="{{ $article->category?->name }}" data-published="{{ $article->published_at?->format('Y-m-d') }}" aria-label="选择 {{ $article->title }}"></td><td><p class="font-medium break-words">{{ $article->title }}</p><p class="topic-help mt-1">{{ Illuminate\Support\Str::limit(strip_tags($article->excerpt??''),240) }}</p></td><td class="whitespace-nowrap">{{ $article->author?->name??'本站' }}<p class="topic-help">可公开阅读 · {{ $article->category?->name }}</p></td><td class="whitespace-nowrap topic-help">{{ $article->published_at?->format('Y-m-d') }}</td></tr>@empty<tr><td colspan="4" class="text-center py-10">当前筛选下没有符合条件的公开文章。</td></tr>@endforelse</tbody></table></div>{{ $articles->links() }}
 <div class="sticky bottom-0 bg-white border-t border-gray-200 py-3 flex justify-end"><a href="{{ $returnUrl }}" class="topic-button topic-primary" data-topic-done>完成选择并返回</a></div>
</div>
<script>
(()=>{const root=document.querySelector('[data-topic-selector]'),key=root.dataset.key;let state;try{state=JSON.parse(sessionStorage.getItem(key)||'null');}catch{}state=state||{entries:[],arrays:{articles:[]},articleOptions:[]};state.arrays||={articles:[]};state.arrays.articles||=[];state.articleOptions||=[];function save(){try{sessionStorage.setItem(key,JSON.stringify(state));}catch{}}function render(){document.querySelector('[data-selected-count]').textContent=state.arrays.articles.length;const box=document.querySelector('[data-topic-selected]');box.replaceChildren();for(const row of state.arrays.articles){const article=state.articleOptions.find(a=>Number(a.article_id)===Number(row.article_id));const b=document.createElement('button');b.type='button';b.className='topic-button';b.textContent=(article?.title||'文章 #'+row.article_id)+' ×';b.addEventListener('click',()=>{state.arrays.articles=state.arrays.articles.filter(a=>Number(a.article_id)!==Number(row.article_id));save();render();});box.append(b);}document.querySelectorAll('[data-topic-choice]').forEach(c=>c.checked=state.arrays.articles.some(a=>Number(a.article_id)===Number(c.value)));}document.querySelectorAll('[data-topic-choice]').forEach(c=>c.addEventListener('change',()=>{const id=Number(c.value);if(c.checked){state.arrays.exclusions=(state.arrays.exclusions||[]).filter(value=>Number(value)!==id);if(!state.arrays.articles.some(a=>Number(a.article_id)===id))state.arrays.articles.push({article_id:id,group:'',reason:''});if(!state.articleOptions.some(a=>Number(a.article_id)===id))state.articleOptions.push({article_id:id,title:c.dataset.title,excerpt:c.dataset.excerpt,url:c.dataset.url,category:c.dataset.category,published_at:c.dataset.published});}else state.arrays.articles=state.arrays.articles.filter(a=>Number(a.article_id)!==id);save();render();}));document.querySelector('[data-select-results]').addEventListener('click',()=>{for(const c of document.querySelectorAll('[data-topic-choice]')){if(!c.checked&&state.arrays.articles.length<200){c.checked=true;c.dispatchEvent(new Event('change'));}}document.querySelector('[data-selector-message]').textContent=state.arrays.articles.length>=200?'最多选择200篇文章，可取消部分选文后继续。':'';});document.querySelector('[data-clear-results]').addEventListener('click',()=>{for(const c of document.querySelectorAll('[data-topic-choice]')){if(c.checked){c.checked=false;c.dispatchEvent(new Event('change'));}}});document.querySelectorAll('[data-topic-done]').forEach(a=>a.addEventListener('click',save));render();})();
</script>
@endsection