@extends('admin.layouts.app')
@section('topbar-title','检查批次')
@section('content')
@include('admin.topics._style')
<div class="topic-shell space-y-5"><div><h1 class="text-2xl font-semibold">检查批次</h1><p class="topic-help mt-2">确认本批的站点、标题数量与处理方式后开始执行。</p></div><section class="topic-panel"><dl class="grid gap-4 sm:grid-cols-4"><div><dt class="topic-help">站点</dt><dd class="font-medium mt-1">{{ $sites[$site]??$site }}</dd></div><div><dt class="topic-help">专题数</dt><dd class="font-medium mt-1">{{ count($rows) }}</dd></div><div><dt class="topic-help">模板</dt><dd class="font-medium mt-1">{{ app(\App\Services\Topics\TopicTemplateCatalog::class)->options($site)[$settings['template_key']] }}</dd></div><div><dt class="topic-help">处理方式</dt><dd class="font-medium mt-1">{{ $settings['mode']==='draft'?'只创建标题草稿':['auto_publish'=>'生成后自动发布','draft_only'=>'生成后保存草稿','review_then_publish'=>'生成后提交审核'][$settings['after']] }}</dd></div></dl></section><form method="POST" action="{{ route('admin.topics.batches.store') }}">@csrf<input type="hidden" name="site" value="{{ $site }}"><input type="hidden" name="request_key" value="{{ $requestKey }}">@foreach($settings as $key=>$value)
@if(is_array($value))
@foreach($value as $item)<input type="hidden" name="{{ $key }}[]" value="{{ $item }}">@endforeach
@else<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endif
@endforeach<div class="overflow-x-auto bg-white border border-gray-200 rounded-lg"><table><thead><tr><th>行</th><th>专题标题与本行配置</th><th>检查结果</th></tr></thead><tbody>@foreach($rows as $row)<tr id="preview-row-{{ $row['number'] }}"><td>{{ $row['number'] }}</td><td>{{ $row['title'] }}<input type="hidden" name="rows[{{ $row['number']-1 }}][title]" value="{{ $row['title'] }}">@foreach($row['metadata']??[] as $key=>$value)<p class="topic-help mt-1">{{ ['audience'=>'目标读者','category'=>'分类','tags'=>'标签','template'=>'模板','freshness'=>'时效','sourcecoverage'=>'来源范围'][$key]??$key }}：{{ $value }}</p><input type="hidden" name="rows[{{ $row['number']-1 }}][metadata][{{ $key }}]" value="{{ $value }}">@endforeach</td><td class="{{ $row['error']?'text-red-700':'text-gray-600' }}">@if($row['error']){{ $row['error'] }}@elseif($row['duplicate_of'])重复，<a class="text-blue-600" href="#preview-row-{{ $row['duplicate_of'] }}">第 {{ $row['duplicate_of'] }} 行为首条</a>，将保留首条结果@elseif($row['existing_id'])已有同主题专题，<a class="text-blue-600" href="{{ $row['existing_url'] }}">查看专题 #{{ $row['existing_id'] }}</a>，将保留其状态@else 可执行 @endif</td></tr>@endforeach</tbody></table></div><div class="flex flex-wrap gap-2 mt-5"><button name="intent" value="batch" class="topic-button topic-primary" @disabled($executableCount===0)>确认配置并开始{{ $settings['mode']==='draft'?'创建草稿':'生成' }}</button><button name="intent" value="task" class="topic-button" @disabled($executableCount===0)>转为专题任务</button><a class="topic-button" href="{{ route('admin.topics.batches.create',['site'=>$site]) }}">返回修改标题</a></div>@if($hasErrors)<p class="topic-help mt-3">当前有 {{ $executableCount }} 个正常项可执行。有错误的行会保留失败回执，你也可以返回修正后重新检查。</p>@endif<p class="topic-help mt-3">开始后按统一设置与本行配置执行，本行模板优先。取消会保留已完成的专题。转为任务会带入有效标题和完整配置，保存时导入标题库。同标题不同范围会保留，生成的专题仍使用原始标题。</p></form></div>
@endsection