@extends('admin.layouts.app')
@section('topbar-title','批量新建专题')
@section('content')
@php($savedBatchForm=session('topic_batch_form.'.$site,[]))
@include('admin.topics._style')
<div class="topic-shell space-y-5"><div><a class="text-blue-600 text-sm" href="{{ route('admin.topics.index',['site'=>$site]) }}">← 专题列表</a><h1 class="text-2xl font-semibold mt-2">批量新建专题</h1><p class="topic-help mt-2">粘贴标题或上传 UTF-8 CSV，先检查逐行预览。每批最多 100 个标题。</p></div>
 <form data-topic-template-form data-template-current-site="{{ $site }}" data-template-url="{{ route('admin.topics.settings') }}" method="POST" enctype="multipart/form-data" action="{{ route('admin.topics.batches.preview') }}" class="space-y-5">@csrf <section class="topic-panel space-y-4"><div class="grid gap-4 sm:grid-cols-2"><div><label>站点</label><select name="site" data-topic-template-site>@foreach($sites as $key=>$label)<option value="{{ $key }}" @selected(old('site',$site)===$key)>{{ $label }}</option>@endforeach</select></div><div><label>创建方式</label><select name="mode" data-batch-mode><option value="ai" @selected(old('mode',$savedBatchForm['mode']??'ai')==='ai')>AI 匹配与生成</option><option value="draft" @selected(old('mode',$savedBatchForm['mode']??'ai')==='draft')>只创建标题草稿</option></select></div></div><div><label>专题标题，每行一个</label><textarea name="titles_text" rows="9" placeholder="输入专题标题">{{ old('titles_text',$savedBatchForm['titles_text']??'') }}</textarea>@error('titles_text')<p class="topic-error">{{ $message }}</p>@enderror</div><div><label>或上传 CSV 文件</label><input type="file" name="csv" accept=".csv,text/csv"><p class="topic-help mt-2">单列可直接导入，多列按 title 或「标题」表头定位，标题可在任意列。支持 UTF-8 BOM、引号内逗号和换行。</p><details class="mt-3"><summary class="text-sm text-blue-600 cursor-pointer">可选列与格式说明</summary><p class="topic-help mt-2">audience／适合人群（读者）、category／文章分类（现有分类名称或 ID）、tags（逗号或分号分隔）、template（使用下方模板标识，可包含主题提供的布局）、sourcecoverage／来源覆盖期／适用范围与限制（来源范围）会保存到每行草稿。本行配置优先于统一设置。</p><p class="topic-help mt-2">freshness／时效模式可用 evergreen、none、annual:2026、monthly:2026-10 等模式；需要依据和期限的模式可追加 ;coverage_note=人工核对依据;valid_until=2026-10-31。请使用真实核对日期和范围。无时效列时沿用默认配置。</p></details>@error('csv')<p class="topic-error">{{ $message }}</p>@enderror</div></section>
 <section class="topic-panel space-y-4"><h2 class="text-lg font-semibold">统一设置</h2><div class="grid gap-4 sm:grid-cols-2"><div data-ai-setting><label>AI 模型</label><select name="model_id"><option value="">选择模型</option>@foreach($models as $model)<option value="{{ $model->id }}" @selected(old('model_id',$savedBatchForm['model_id']??'')==$model->id)>{{ $model->name }}</option>@endforeach</select>@error('model_id')<p class="topic-error">{{ $message }}</p>@enderror</div><div><label>专题模板</label><select name="template_key" data-topic-template-select>@foreach(app(\App\Services\Topics\TopicTemplateCatalog::class)->options($site) as $key=>$label)<option value="{{ $key }}" @selected(old('template_key',$savedBatchForm['template_key']??'default')===$key)>{{ $label }}（{{ $key }}）</option>@endforeach</select></div><div data-ai-setting><label>生成后处理</label><select name="after">@foreach(['auto_publish'=>'自动发布','draft_only'=>'仅保存草稿','review_then_publish'=>'审核后发布'] as $key=>$label)<option value="{{ $key }}" @selected(old('after',$savedBatchForm['after']??'auto_publish')===$key)>{{ $label }}</option>@endforeach</select></div><div data-ai-setting><label>期望选文数量</label><input type="number" name="target_count" min="2" max="24" value="{{ old('target_count',$savedBatchForm['target_count']??8) }}"></div></div><div><label for="batch-categories">文章分类范围，可选</label><select id="batch-categories" name="category_ids[]" multiple size="4">@foreach($categories as $category)<option value="{{ $category->id }}" @selected(in_array($category->id,old('category_ids',$savedBatchForm['category_ids']??[])))>{{ $category->name }}</option>@endforeach</select><p class="topic-help mt-2">不选择时从本站公开文章中匹配。CSV 的文章分类优先于统一范围。</p>@error('category_ids')<p class="topic-error">{{ $message }}</p>@enderror</div><div data-ai-setting><label>生成规则，可选</label><textarea name="rules" rows="3">{{ old('rules',$savedBatchForm['rules']??'') }}</textarea></div><p class="topic-help" data-topic-template-message role="status"></p><p class="topic-help">来源不足、重复与执行失败分别记录。只创建标题草稿时无需 AI。</p><div class="flex flex-wrap gap-2"><button name="intent" value="batch" class="topic-button topic-primary">检查标题与配置</button><button name="intent" value="task" class="topic-button">转为专题任务</button></div><p class="topic-help mt-2">转为任务会带入有效标题和当前设置，保存任务时导入标题库。同标题不同范围会分别生成专题，并在标题库中附带范围说明；任务页可选择启用时间与处理方式。</p></section></form></div>
<script>(()=>{const select=document.querySelector('[data-batch-mode]');const change=()=>document.querySelectorAll('[data-ai-setting]').forEach(n=>n.hidden=select.value==='draft');select.addEventListener('change',change);change();})();</script>
<script src="{{ asset('admin/topic-editor.js') }}" defer></script>
@endsection