@extends('admin.layouts.app')
@section('topbar-title',$topic?'编辑专题':'新建专题')
@section('content')
@include('admin.topics._style')
@php
$token=(string)request('form_token',$formToken);$formKey='geoflow:topic:'.$site.':'.($topic?'topic-'.$topic->id:'new-'.$token);
$draft=$payload;
if(array_key_exists('title',old())){
    $draft=array_replace_recursive($payload,old());
    foreach(['articles','summary.facts','faq','basic_info','score.dimensions','score.evidence','score.weights','source_overrides.excluded_article_ids'] as $path){data_set($draft,$path,data_get(old(),$path,[]));}
    if(array_key_exists('score',old()) && old('score')===null){$draft['score']=null;}
}
$articleOptions=$sourceOptions;
$initialEditorData=['payload'=>$draft,'articles'=>$articleOptions];
@endphp
<div class="topic-shell space-y-5">
 <div class="flex flex-wrap justify-between gap-3"><div><a class="text-sm text-blue-600" data-topic-list-back href="{{ $listReturn }}">← 专题列表</a><h1 class="text-2xl font-semibold mt-2">{{ $topic?'编辑专题':'新建专题' }}</h1><p class="topic-help mt-2">{{ $sites[$site]??$site }} · {{ $state }} · {{ $topic?'工作稿 v'.$topic->draft_version:'填写标题即可保存草稿' }}@if($topic?->publicRevision) · 公开版 v{{ $topic->publicRevision->number }}@endif</p></div>@if($topic)<div class="flex flex-wrap gap-2">@if($publicUrl)<a class="topic-button" href="{{ $publicUrl }}" target="_blank" rel="noopener">查看公开页</a>@endif <a class="topic-button" href="{{ route('admin.topics.history',['topic'=>$topic->id,'list_return'=>$listReturn]) }}">版本历史</a><a class="topic-button" href="{{ route('admin.tasks.create',['content_type'=>'topic','fromTopic'=>$topic->id,'site'=>$site]) }}">创建维护任务</a></div>@endif</div>
 <form id="topic-editor-form" method="POST" action="{{ $topic?route('admin.topics.update',['topic'=>$topic->id]):route('admin.topics.store') }}" data-topic-editor data-has-errors="{{ $errors->any()?'true':'false' }}" data-storage-key="{{ $formKey }}" data-saved="{{ session('topic_form_saved')?'true':'false' }}" class="space-y-5">@csrf @if($topic)@method('PUT')@endif
 <input type="hidden" name="list_return" value="{{ $listReturn }}"><input type="hidden" name="source_overrides_present" value="1"><input type="hidden" name="site" value="{{ $site }}"><input type="hidden" name="expected_version" value="{{ old('expected_version',$topic?->draft_version) }}"><input type="hidden" name="request_key" value="{{ (string) Illuminate\Support\Str::uuid() }}">
 <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><div class="space-y-5 min-w-0">
 <section class="topic-panel space-y-4"><h2 class="font-semibold text-lg">标题与导语</h2><div><label for="topic-title">专题标题 *</label><input id="topic-title" name="title" required maxlength="200" value="{{ old('title',$payload['title']) }}">@error('title')<p class="topic-error">{{ $message }}</p>@enderror</div><div><label for="intro">导语</label><textarea name="intro" id="intro" rows="5" placeholder="说明专题覆盖什么、适合谁阅读。">{{ old('intro',$payload['intro']??'') }}</textarea>@error('intro')<p class="topic-error">{{ $message }}</p>@enderror</div><div><label for="tags_text">标签，可选</label><input name="tags_text" id="tags_text" value="{{ old('tags_text',implode('，',$payload['tags']??[])) }}" placeholder="用逗号分隔">@error('tags')<p class="topic-error">{{ $message }}</p>@enderror</div></section>
 <section class="topic-panel"><div class="flex flex-wrap items-center justify-between gap-2"><div><h2 class="text-lg font-semibold">选文与顺序</h2><p class="topic-help mt-1">发布需要至少两篇不同正文的本站公开文章。</p></div><a class="topic-button" data-topic-picker href="{{ route('admin.topics.articles',['site'=>$site,'topic'=>$topic?->id,'form_key'=>$formKey,'form_token'=>$token,'list_return'=>$listReturn]) }}">选择文章</a></div><div data-topic-array="articles" class="mt-4"></div><details class="mt-4"><summary class="text-sm text-blue-600 cursor-pointer">永久排除的文章（<span data-exclusion-count>0</span>）</summary><p class="topic-help mt-2">永久排除后，后续 AI 和自动维护不会重新匹配。可在这里解除，或在选择文章页明确选回。保存工作稿后生效。</p><div data-topic-exclusions class="space-y-2 mt-3"></div></details>@foreach($errors->getMessages() as $key=>$messages)@if(str_starts_with($key,'articles'))<p class="topic-error">{{ $messages[0] }}</p>@endif @endforeach <button class="topic-button mt-4" type="submit" name="action" value="verify_sources">核对来源后保存</button><p class="topic-help mt-2">确认选文当前正文与摘要后使用。来源变化时，发布会提示重新核对。</p></section>
 <section class="topic-panel space-y-4"><h2 class="text-lg font-semibold">结构化摘要，可选</h2>@foreach($errors->getMessages() as $key=>$messages)@if(str_starts_with($key,'summary.')&&!str_starts_with($key,'summary.facts'))<p class="topic-error">{{ $messages[0] }}</p>@endif @endforeach<div><label>一句话结论</label><input name="summary[one_sentence]" value="{{ old('summary.one_sentence',$payload['summary']['one_sentence']??'') }}"></div><div><label>事实与出处</label><p class="topic-help">选择支持事实的文章，并粘贴每篇来源中的原文片段。AI 生成会自动附上定位依据；保存草稿可以稍后补充。</p><div data-topic-array="facts"></div><button class="topic-button mt-2" type="button" data-topic-add="facts">添加事实</button>@foreach($errors->getMessages() as $key=>$messages)@if(str_starts_with($key,'summary.facts'))<p class="topic-error">{{ $messages[0] }}</p>@endif @endforeach</div><div><label>适用范围与限制</label><p class="topic-help">同名专题可在这里写清不同的适用范围，系统按主题和范围检查重复。</p><textarea name="summary[scope]" rows="2">{{ old('summary.scope',$payload['summary']['scope']??'') }}</textarea></div><div><label>阅读建议</label><textarea name="summary[reading_advice]" rows="2">{{ old('summary.reading_advice',$payload['summary']['reading_advice']??'') }}</textarea></div></section>
 <details class="topic-panel"><summary>时间范围与基本信息</summary>@foreach($errors->getMessages() as $key=>$messages)@if(str_starts_with($key,'freshness')||str_starts_with($key,'basic_info'))<p class="topic-error">{{ $messages[0] }}</p>@endif @endforeach
@include('admin.topics._freshness-fields',['freshnessValues'=>$payload['freshness']??[]])<div data-topic-array="basic_info" class="mt-4"></div><button type="button" class="topic-button mt-2" data-topic-add="basic_info">添加基本信息</button></details>
 <details class="topic-panel"><summary>搜索展示与地址，高级设置</summary><div class="space-y-4 mt-4"><p class="topic-help">可选的搜索标题与描述用于搜索展示，正文标题保持独立。留空使用专题内容。</p><div><label for="topic-seo-title">搜索标题，可选</label><input id="topic-seo-title" name="seo[title]" maxlength="200" value="{{ old('seo.title',$payload['seo']['title']??'') }}">@error('seo.title')<p class="topic-error">{{ $message }}</p>@enderror</div><div><label for="topic-seo-description">搜索描述，可选</label><textarea id="topic-seo-description" name="seo[description]" maxlength="500" rows="3">{{ old('seo.description',$payload['seo']['description']??'') }}</textarea>@error('seo.description')<p class="topic-error">{{ $message }}</p>@enderror</div>@if($topic?->exists)<a data-preserve-topic class="topic-button" href="{{ route('admin.topics.paths.edit',['topic'=>$topic->id]) }}">管理专题地址</a>@endif</div></details>
 <details class="topic-panel"><summary>文章匹配规则，可选</summary><div class="mt-4">@include('admin.topics._matching-fields',['matchingValues'=>$payload['matching_rules']??[]])</div></details>
 <details class="topic-panel"><summary>常见问题，可选</summary><div data-topic-array="faq" class="mt-4"></div><button type="button" class="topic-button mt-2" data-topic-add="faq">添加问题</button>@foreach($errors->getMessages() as $key=>$messages)@if(str_starts_with($key,'faq'))<p class="topic-error">{{ $messages[0] }}</p>@endif @endforeach</details>
 <details class="topic-panel"><summary>评分，可选</summary>@foreach($errors->getMessages() as $key=>$messages)@if(str_starts_with($key,'score'))<p class="topic-error">{{ $messages[0] }}</p>@endif @endforeach<div class="space-y-4 mt-4"><label><input type="checkbox" name="score[enabled]" value="1" @checked(old('score.enabled',$payload['score']['enabled']??false))> 启用有依据的评分</label><p class="topic-help">各维度 0–10 分，按权重计算总分。评分过期或依据变化后隐藏，专题仍可发布。</p><div class="grid gap-4 sm:grid-cols-2"><div><label>评分类型</label><select name="score[type]"><option value="editorial" @selected(old('score.type',$payload['score']['type']??'editorial')==='editorial')>编辑评分</option><option value="ai_assisted" @selected(old('score.type',$payload['score']['type']??'')==='ai_assisted')>AI 辅助评分</option></select></div>@foreach(['name'=>'评分名称','source'=>'评分来源','total'=>'总分（0–10）','rated_at'=>'真实评分日期','valid_until'=>'有效期至'] as $key=>$label)<div><label>{{ $label }}</label><input name="score[{{ $key }}]" type="{{ in_array($key,['rated_at','valid_until'])?'date':($key==='total'?'number':'text') }}" @if($key==='total') min="0" max="10" step="0.1" @endif value="{{ old('score.'.$key,$key==='rated_at'?substr($payload['score'][$key]??'',0,10):($payload['score'][$key]??'')) }}"></div>@endforeach</div><div data-topic-array="dimensions"></div><button type="button" class="topic-button" data-topic-add="dimensions">添加维度与权重</button><div data-topic-array="evidence"></div><button type="button" class="topic-button" data-topic-add="evidence">添加评分依据</button></div></details>
 </div><aside class="space-y-5 min-w-0"><section class="topic-panel space-y-4"><h2 class="text-lg font-semibold">内容呈现</h2><div><label>频道展示顺序，可选</label><input type="number" name="display_order" min="-1000000" max="1000000" value="{{ old('display_order',$topic?->display_order??0) }}"><p class="topic-help mt-2">数值小的专题优先，同值按首次公开时间排序。</p>@error('display_order')<p class="topic-error">{{ $message }}</p>@enderror</div><div><label>专题模板</label><select name="template_key">@foreach(app(\App\Services\Topics\TopicTemplateCatalog::class)->options($site) as $key=>$label)<option value="{{ $key }}" @selected(old('template_key',$payload['template_key']??'default')===$key)>{{ $label }}</option>@endforeach</select><p class="topic-help mt-2">切换模板直接使用当前内容。</p></div><button type="submit" name="action" value="save" class="topic-button topic-primary w-full">保存工作稿</button><button type="submit" name="action" value="publish" class="topic-button topic-primary w-full">{{ $settings['require_review']?'保存并提交审核':'保存并发布' }}</button><button type="submit" name="action" value="preview" class="topic-button w-full">保存并预览</button><a data-preserve-topic class="text-sm text-blue-600 inline-block" href="{{ route('admin.topics.settings',['site'=>$site,'topic'=>$topic?->id,'form_token'=>$token,'list_return'=>$listReturn]) }}">查看本站专题设置</a><p class="topic-help">Ctrl / ⌘ + S 保存工作稿。保存与预览保持当前公开版。{{ $settings['require_review']?'本站发布后需要审核。':'本站可直接发布。' }}</p>@error('expected_version')<p class="topic-error">{{ $message }}</p>@enderror @error('draft_version')<p class="topic-error">{{ $message }}</p>@enderror</section>
 <details class="topic-panel" open><summary>AI 辅助，可选</summary><div class="space-y-4 mt-3">@if($models->isEmpty())<p class="topic-help">当前没有可用模型，手工编辑和发布可以继续。</p><a class="topic-button" data-preserve-topic href="{{ route('admin.ai-models.index') }}" target="_blank" rel="noopener">配置 AI 模型</a><a class="topic-button" data-preserve-topic href="{{ request()->fullUrl() }}">配置后刷新模型</a>@endif<label>AI 模型<select name="model_id"><option value="">选择模型</option>@foreach($models as $model)<option value="{{ $model->id }}" @selected((int)old('model_id')===$model->id)>{{ $model->name }}</option>@endforeach</select></label>@error('model_id')<p class="topic-error">{{ $message }}</p>@enderror<label>期望选文数量<input type="number" min="2" max="24" name="target_count" value="{{ old('target_count',8) }}"></label><label>补充要求<textarea name="rules" rows="3">{{ old('rules') }}</textarea></label><label>生成范围<select name="field"><option value="">完整内容</option>@foreach(['intro'=>'导语','summary'=>'摘要','tags'=>'标签','articles'=>'选文','seo'=>'搜索文案','faq'=>'常见问题','basic_info'=>'基本信息'] as $key=>$label)<option value="{{ $key }}" @selected(old('field')===$key)>{{ $label }}</option>@endforeach</select></label><button class="topic-button w-full" type="submit" name="action" value="generate">保存并获取 AI 建议</button><p class="topic-help">{{ $topic?'保留人工内容，生成建议供对照采用。':'先保存绑定的草稿，再开始生成；完成后保持草稿。' }}</p></div></details>
 @if($runs->isNotEmpty())<section class="topic-panel"><h2 class="font-semibold mb-3">生成记录</h2>@foreach($runs as $run)<p class="text-sm py-1"><a class="text-blue-600" href="{{ route('admin.topics.runs.show',['run'=>$run->id]) }}">生成 #{{ $run->id }}</a> · {{ ['pending'=>'等待执行','running'=>'正在生成','completed'=>'已完成','needs_adoption'=>'等待采用建议','duplicate'=>'已有相同专题','cancelled'=>'已取消','waiting_content'=>'等待补充来源','failed'=>'生成失败','publication_failed'=>'发布失败'][$run->status]??'查看处理结果' }}</p>@endforeach</section>@endif
 </aside></div><script type="application/json" data-topic-initial>@json($initialEditorData)</script>
 </form>
 @if($topic)<section class="topic-panel">@if($topic->pending_revision_id)<p class="topic-help mb-3">{{ $topic->approved_revision_id=== $topic->pending_revision_id?'已审核，等待任务按计划发布。':'待审核版保持提交时的内容，请先预览固定版本再审核。' }} <a class="text-blue-600" href="{{ route('admin.topics.revisions.preview',['topic'=>$topic->id,'revision'=>$topic->pending_revision_id]) }}">预览审核版本</a></p>@endif <div class="flex flex-wrap gap-2">@foreach(['approve'=>'通过审核','withdraw'=>'撤回公开版','trash'=>'移入回收站'] as $action=>$label)@if(($action!=='approve'||($topic->pending_revision_id&&!$topic->approved_revision_id))&&($action!=='withdraw'||$topic->public_revision_id))<form method="POST" action="{{ route('admin.topics.action',['topic'=>$topic->id,'action'=>$action]) }}">@csrf<input type="hidden" name="site" value="{{ $site }}"><input type="hidden" name="expected_version" value="{{ $topic->draft_version }}"><input type="hidden" name="expected_revision_id" value="{{ $action==='approve'?$topic->pending_revision_id:$topic->public_revision_id }}"><input type="hidden" name="request_id" value="{{ (string) Illuminate\Support\Str::uuid() }}"><button class="topic-button {{ $action==='publish'?'topic-primary':'' }}">{{ $action==='approve'&&$topic->task_id?'通过审核，按计划发布':$label }}</button></form>@endif @endforeach</div><p class="topic-help mt-3">“保存并发布”使用当前页面内容。待审核版固定，之后编辑继续保存在工作稿中。</p></section>@endif
</div>
<script src="{{ asset('admin/topic-editor.js') }}" defer></script>
@endsection