@extends('admin.layouts.app')
@section('topbar-title','专题列表')
@section('content')
@include('admin.topics._style')
<div data-topic-list data-site="{{ $site }}" class="topic-shell space-y-6">
 <div class="flex flex-wrap items-start justify-between gap-4"><div class="min-w-0 max-w-full"><h1 class="text-2xl font-semibold text-gray-900">专题列表</h1><p class="topic-help mt-2">以本站公开文章组织可持续更新的专题。</p><div class="mt-4"><x-admin.v3.articles-subnav active="topics" /></div></div><div class="topic-actions flex flex-wrap gap-2"><a class="topic-button topic-primary" href="{{ route('admin.topics.create',['site'=>$site]) }}">新建专题</a><a class="topic-button" href="{{ route('admin.topics.batches.create',['site'=>$site]) }}">批量新建</a><a class="topic-button" href="{{ route('admin.tasks.create',['content_type'=>'topic','site'=>$site]) }}">创建专题任务</a><a class="topic-button" href="{{ route('admin.topics.settings',['site'=>$site]) }}">专题设置</a></div></div>
 @if(session('bulk_results'))<div class="topic-panel"><h2 class="font-semibold mb-3">批量操作结果</h2>@foreach(session('bulk_results') as $result)<p class="text-sm py-1 {{ $result['ok']?'text-green-700':'text-red-700' }}"><a href="{{ $result['url']??route('admin.topics.history',['topic'=>$result['id']]) }}">专题 #{{ $result['id'] }}</a>：{{ $result['message'] }} @if(!empty($result['run_url']))<a class="text-blue-600" href="{{ $result['run_url'] }}">查看生成记录</a>@endif</p>@endforeach</div>@endif
 <form method="GET" class="topic-panel grid gap-4 sm:grid-cols-5"><div><label for="site">站点</label><select id="site" name="site">@foreach($sites as $key=>$name)<option value="{{ $key }}" @selected($site===$key)>{{ $name }}</option>@endforeach</select></div><div><label for="status">状态</label><select name="status" id="status"><option value="">全部状态</option>@foreach(['draft'=>'草稿','pending'=>'待审核','scheduled'=>'已审核，等待计划发布','published'=>'已公开','withdrawn'=>'已撤回','missing_sources'=>'缺来源','trash'=>'回收站'] as $key=>$label)<option value="{{ $key }}" @selected($status===$key)>{{ $label }}</option>@endforeach</select></div><div><label for="search">标题</label><input name="search" id="search" value="{{ request('search') }}" placeholder="搜索专题标题"></div><div><label for="task-filter">来源任务</label><select id="task-filter" name="task_id"><option value="">全部任务</option>@foreach($topicTasks as $sourceTask)<option value="{{ $sourceTask->id }}" @selected(request('task_id')==$sourceTask->id)>{{ $sourceTask->name }}</option>@endforeach</select></div><div class="flex items-end gap-2"><button class="topic-button topic-primary">筛选</button><a class="topic-button" href="{{ route('admin.topics.index',['site'=>$site]) }}">重置</a></div></form>
 <form method="POST" action="{{ route('admin.topics.bulk') }}" data-topic-bulk>@csrf<input type="hidden" name="site" value="{{ $site }}"><input type="hidden" name="request_id" value="{{ (string) Illuminate\Support\Str::uuid() }}">
 @if($topics->isNotEmpty()&&$status!=='trash')<div class="flex flex-wrap gap-2 mb-3"><select name="action" aria-label="批量操作" style="width:auto"><option value="generate">批量获取 AI 建议</option><option value="retry_generation">重试所选失败建议</option><option value="publish">批量发布</option><option value="withdraw">批量撤回</option><option value="trash">移入回收站</option></select><button class="topic-button" data-bulk-execute disabled>执行所选</button><span class="topic-help self-center" data-bulk-count>已选 0 个</span><p class="topic-help self-center">逐项处理并保留回执。批量 AI 只获取建议，人工内容需选择采用。</p></div>@endif
 <section class="topic-panel space-y-3 mb-4" data-bulk-ai><h2 class="font-semibold">本次 AI 建议</h2><div class="grid gap-4 sm:grid-cols-2"><div><label>AI 模型</label><select name="model_id"><option value="">选择模型</option>@foreach($models as $model)<option value="{{ $model->id }}">{{ $model->name }}</option>@endforeach</select>@error('model_id')<p class="topic-error">{{ $message }}</p>@enderror</div><div><label>期望选文数量</label><input type="number" name="target_count" min="2" max="24" value="8"></div></div><div><label>生成规则，可选</label><textarea name="rules" rows="3" placeholder="说明选文范围、语气或阅读分组。">{{ old('rules') }}</textarea></div><p class="topic-help">仅为上方所选专题排队，结果可逐块对照采用。失败重试沿用原生成配置。</p></section>
 <div class="overflow-x-auto border border-gray-200 rounded-lg bg-white"><table class="topic-list-table"><thead><tr><th class="w-10">@if($status!=='trash')<input type="checkbox" data-bulk-all aria-label="选择当前页专题">@else 选择 @endif</th><th>专题标题</th><th>状态</th><th>工作稿 / 公开版</th><th>有效文章</th><th>公开更新</th><th>操作</th></tr></thead><tbody>@forelse($topics as $topic)<tr><td>@if(!$topic->trashed())<input type="checkbox" name="topic_ids[]" value="{{ $topic->id }}" aria-label="选择 {{ $topic->title }}"><input type="hidden" name="versions[{{ $topic->id }}][draft]" value="{{ $topic->draft_version }}"><input type="hidden" name="versions[{{ $topic->id }}][public]" value="{{ $topic->public_revision_id }}">@endif</td><td><a class="font-medium text-blue-600 break-words" href="{{ $topic->trashed()?route('admin.topics.history',['topic'=>$topic->id]):route('admin.topics.edit',['topic'=>$topic->id,'list_return'=>request()->fullUrl()]) }}">{{ $topic->title }}</a><p class="topic-help">#{{ $topic->id }} @if($topic->task_id) · <a href="{{ route('admin.tasks.edit',['taskId'=>$topic->task_id]) }}">{{ $topic->task?->name??('任务 #'.$topic->task_id) }}</a>@else · @if(!empty($topicDetails[$topic->id]['batch_id']))<a class="text-blue-600" href="{{ route('admin.topics.batches.show',['batch'=>$topicDetails[$topic->id]['batch_id']]) }}">批次 #{{ $topicDetails[$topic->id]['batch_id'] }}</a>@else {{ $topicDetails[$topic->id]['origin']??'手工创建' }} @endif @endif</p>@if(!empty($topicDetails[$topic->id]['scope']))@if(mb_strlen($topicDetails[$topic->id]['scope'])>160)<details class="mt-1"><summary class="topic-help">范围：{{ mb_substr($topicDetails[$topic->id]['scope'],0,160) }}…</summary><p class="topic-help mt-1">{{ $topicDetails[$topic->id]['scope'] }}</p></details>@else<p class="topic-help mt-1">范围：{{ $topicDetails[$topic->id]['scope'] }}</p>@endif
@endif @if(!empty($topicDetails[$topic->id]['intro']))<p class="topic-help mt-2">{{ $topicDetails[$topic->id]['intro'] }}</p>@endif</td><td>{{ $states[$topic->id] }}</td><td class="whitespace-nowrap">工作稿 v{{ $topic->draft_version }}<br>{{ $topic->publicRevision?'公开版 v'.$topic->publicRevision->number:'尚未公开' }}</td><td>{{ $topicDetails[$topic->id]['count']??0 }} 篇</td><td class="whitespace-nowrap topic-help">{{ !empty($topicDetails[$topic->id]['public_updated'])?\Carbon\CarbonImmutable::parse($topicDetails[$topic->id]['public_updated'])->format('Y-m-d H:i'):'尚未公开' }}</td><td>@if($topic->trashed())<button type="submit" class="text-blue-600" formaction="{{ route('admin.topics.action',['topic'=>$topic->id,'action'=>'restore']) }}">恢复到草稿</button>@else<a class="text-blue-600" href="{{ $topic->pending_revision_id?route('admin.topics.revisions.preview',['topic'=>$topic->id,'revision'=>$topic->pending_revision_id]):route('admin.topics.preview',['topic'=>$topic->id]) }}">预览</a>@endif</td></tr>@empty<tr><td colspan="7" class="text-center py-12"><p class="font-medium text-gray-800">{{ $status==='trash'?'回收站为空':'当前筛选下没有专题' }}</p><p class="topic-help mt-2">先保存标题即可建立草稿；填写导语并选择两篇不同正文的本站公开文章后可发布。</p></td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $topics->links() }}</div></form>
</div>
<script>(()=>{const f=document.querySelector('[data-topic-bulk]');if(!f)return;const boxes=[...f.querySelectorAll('[name="topic_ids[]"]')],all=f.querySelector('[data-bulk-all]'),count=f.querySelector('[data-bulk-count]'),execute=f.querySelector('[data-bulk-execute]');function update(){const n=boxes.filter(c=>c.checked).length;if(count)count.textContent='已选 '+n+' 个';if(execute)execute.disabled=n===0;if(all){all.checked=boxes.length>0&&n===boxes.length;all.indeterminate=n>0&&n<boxes.length;}}boxes.forEach(c=>c.addEventListener('change',update));all?.addEventListener('change',()=>{boxes.forEach(c=>c.checked=all.checked);update();});window.addEventListener('pageshow',()=>{boxes.forEach(c=>c.checked=false);update();});const action=f.querySelector('[name=action]'),ai=f.querySelector('[data-bulk-ai]');function aiState(){if(ai)ai.hidden=action?.value!=='generate';}action?.addEventListener('change',aiState);aiState();update();})();</script>
<script src="{{ asset('admin/topic-editor.js') }}" defer></script>
@endsection