@extends('admin.layouts.app')
@section('topbar-title','专题预览')
@section('content')
@include('admin.topics._style')
<div class="topic-shell space-y-5"><div class="topic-panel flex flex-wrap items-center justify-between gap-3"><div><h1 class="font-semibold">专题预览 · {{ $sites[$site]??$site }}</h1><p class="topic-help mt-1">此页面需要管理员登录，保持未公开。模板：{{ app(\App\Services\Topics\TopicTemplateCatalog::class)->options($site)[$topicView['template_key']]??$topicView['template_key'] }}</p></div><a class="topic-button" href="{{ $topic->trashed()?route('admin.topics.history',['topic'=>$topic->id,'list_return'=>request()->query('list_return')]):route('admin.topics.edit',['topic'=>$topic->id,'list_return'=>request()->query('list_return')]) }}">返回编辑</a></div>
 @foreach($topicView['warnings'] as $warning)<p class="topic-panel text-amber-800">{{ $warning }}</p>@endforeach
 <article class="topic-panel space-y-6"><header><h2 class="text-3xl font-semibold leading-snug text-blue-900">{{ $topicView['title'] }}</h2>@if($topicView['intro'])<p class="mt-4 text-base leading-8 whitespace-pre-line">{{ $topicView['intro'] }}</p>@endif</header>
 @if(array_filter($topicView['summary']))<section class="space-y-3"><h2 class="text-xl font-semibold">结构化摘要</h2><p class="font-medium">{{ $topicView['summary']['one_sentence'] }}</p>@foreach($topicView['summary']['facts'] as $fact)<p class="leading-7">{{ $fact['text'] }} @foreach($fact['article_ids'] as $id)@php($source=collect($topicView['articles'])->firstWhere('id',$id))@if($source)<a class="text-blue-600 text-sm" href="{{ $source['url'] }}">[{{ $source['title'] }}]</a>@endif @endforeach</p>@endforeach @if($topicView['summary']['scope'])<p>适用范围与限制：{{ $topicView['summary']['scope'] }}</p>@endif @if($topicView['summary']['reading_advice'])<p>阅读建议：{{ $topicView['summary']['reading_advice'] }}</p>@endif</section>@endif
 <section><h2 class="text-xl font-semibold">{{ $topicView['template_key']==='guide'?'按顺序阅读':($topicView['template_key']==='roundup'?'资讯与来源':'来源文章') }}</h2>@forelse($topicView['articles'] as $source)<div class="topic-row"><p class="topic-help">{{ $source['group'] }}</p><h3 class="font-semibold text-lg"><a class="text-blue-600" href="{{ $source['url'] }}">{{ $source['title'] }}</a></h3><p class="topic-help mt-2">{{ $source['reason']?:$source['excerpt'] }}</p></div>@empty<p class="topic-help mt-4">尚未选择有效来源文章。</p>@endforelse</section>
 @if($topicView['score'])<section><h2 class="text-xl font-semibold">{{ $topicView['score']['name'] }}</h2><p class="text-2xl font-semibold mt-2">{{ $topicView['score']['total'] }} / 10</p><p class="topic-help">{{ $topicView['score']['source'] }} · {{ substr($topicView['score']['rated_at'],0,10) }}</p>@foreach($topicView['score']['dimensions'] as $dimension)<p class="mt-2">{{ $dimension['name'] }}：{{ $dimension['score'] }}</p>@endforeach</section>@endif
 @if($topicView['basic_info'])<section><h2 class="text-xl font-semibold">基本信息</h2><dl>@foreach($topicView['basic_info'] as $info)<div class="topic-row"><dt class="font-medium">{{ $info['label'] }}</dt><dd class="topic-help">{{ $info['value'] }}</dd></div>@endforeach</dl></section>@endif
 @if($topicView['faq'])<section><h2 class="text-xl font-semibold">常见问题</h2>@foreach($topicView['faq'] as $faq)<details class="topic-row"><summary>{{ $faq['question'] }}</summary><p class="mt-2 leading-7">{{ $faq['answer'] }}</p>@foreach($faq['article_ids'] as $id)@php($source=collect($topicView['articles'])->firstWhere('id',$id))@if($source)<a class="text-blue-600 text-sm" href="{{ $source['url'] }}">{{ $source['title'] }}</a>@endif @endforeach</details>@endforeach</section>@endif
 <div class="flex flex-wrap gap-2">@foreach($topicView['tags'] as $tag)<span class="rounded-md bg-blue-50 px-3 py-1 text-sm text-blue-800">{{ $tag }}</span>@endforeach</div></article></div>
@if(session('topic_form_saved') && $topic)<script>try{sessionStorage.removeItem(@json('geoflow:topic:'.$site.':topic-'.$topic->id));}catch{}</script>@endif
@endsection