@extends('admin.layouts.app')
@section('topbar-title','专题生成状态')
@section('content')
@include('admin.topics._style')
@php($labels=['pending'=>'等待执行','running'=>'正在生成','completed'=>'已完成','needs_adoption'=>'等待采用建议','duplicate'=>'已有相同专题','cancelled'=>'已取消','waiting_content'=>'等待补充来源','failed'=>'生成失败','publication_failed'=>'发布失败'])
<div class="topic-shell space-y-5"><div class="flex flex-wrap justify-between gap-3"><div><h1 class="text-2xl font-semibold">生成 #{{ $run->id }}</h1><p class="topic-help mt-2">{{ $sites[$site]??$site }} @if($topic) · {{ $topic->title }}@endif</p></div><a class="topic-button" href="{{ $runData['topic_url']??route('admin.topics.index',['site'=>$site]) }}">返回专题</a></div>
 <section class="topic-panel space-y-3" data-topic-run data-status-url="{{ route('admin.topics.runs.status',['run'=>$run->id]) }}"><h2 class="font-semibold text-lg" data-run-status>{{ $labels[$run->status]??$run->status }}</h2><p class="topic-help" data-run-phase>{{ ['waiting'=>'等待队列','matching'=>'匹配本站公开文章','generating'=>'生成内容','saving'=>'保存草稿','publishing'=>'提交发布','finished'=>'本次处理结束'][$run->phase]??$run->phase }}</p><p class="text-red-700 text-sm" data-run-error>{{ $run->error }}</p>@if($runData['lease_expired'])<p class="topic-help">执行租约已到期，可以恢复。已保存且来源有效的结果会继续使用，旧执行器不能提交内容。</p>@endif<p class="topic-help">这里只显示实际阶段。完成时间由队列执行情况决定。</p><div class="flex flex-wrap gap-2">@if(in_array($run->status,['pending','running'])&&!$runData['lease_expired'])<form method="POST" action="{{ route('admin.topics.runs.action',['run'=>$run->id,'action'=>'cancel']) }}">@csrf<button class="topic-button">取消生成</button></form>@elseif($runData['can_retry']&&!$topic?->trashed())<form method="POST" action="{{ route('admin.topics.runs.action',['run'=>$run->id,'action'=>'retry']) }}">@csrf<button class="topic-button">{{ $runData['lease_expired']?'恢复中断执行':'重试本次生成' }}</button></form>@endif</div></section>
 @if($runData['matching_report'])
 @php($matching=$runData['matching_report'])
 <section class="topic-panel space-y-3"><h2 class="font-semibold text-lg">文章匹配记录</h2><p class="topic-help">{{ $matching['mode']==='manual_selection'?'本次单字段建议使用已核对的选文。':'已扫描本站声明来源范围。' }} 扫描 {{ $matching['scanned_count'] }} 篇 · 公开合格 {{ $matching['eligible_count'] }} 篇 · 命中 {{ $matching['matched_count'] }} 篇 · 不同正文 {{ $matching['distinct_count'] }} 篇 · 候选 {{ $matching['candidate_count'] }} 篇 · AI 阅读 {{ $matching['ai_count'] }} 篇</p><p class="topic-help">{{ $matching['scan_complete']?'扫描已完成。':'扫描尚未完成。' }} {{ $matching['truncated']?'候选按得分与发布时间保留前 100 篇。':'候选范围已完整保留。' }} {{ $matching['ai_truncated']?'AI 阅读范围保留前 40 篇。':'' }}</p>
 @if($matching['mode']==='automatic')<p class="topic-help">基础词：{{ implode('、',$matching['base_terms']??[])?:'未设置，覆盖来源范围' }}@if(!empty($matching['rules']['required_groups'])) · 必须词组：{{ implode('；',array_map(fn($group)=>implode(' / ',$group),$matching['rules']['required_groups'])) }}@endif @if(!empty($matching['rules']['excluded_terms'])) · 排除词：{{ implode('、',$matching['rules']['excluded_terms']) }}@endif</p><p class="topic-help">排除词跳过 {{ $matching['excluded_term_count']??0 }} 篇 · 必须词组未满足 {{ $matching['required_group_miss_count']??0 }} 篇。按标题 6、关键词 3、摘要 3、正文 1 累加命中得分。</p>@endif
 @if(!empty($matching['matches']))<details><summary class="text-sm text-blue-600 cursor-pointer">查看候选与命中解释</summary><div class="overflow-x-auto mt-3"><table class="topic-table"><thead><tr><th>文章</th><th>得分</th><th>命中位置</th></tr></thead><tbody>@foreach($matching['matches'] as $match)<tr><td>{{ $sourceNames[$match['article_id']]??'来源当前不可用' }} · #{{ $match['article_id'] }}</td><td>{{ $match['score'] }}</td><td>@foreach($match['hits'] as $hit)<span class="inline-block text-xs mr-2">{{ $hit['term'] }} / {{ ['title'=>'标题','keywords'=>'关键词','excerpt'=>'摘要','body'=>'正文'][$hit['field']]??'内容' }} +{{ $hit['weight'] }}</span>@endforeach</td></tr>@endforeach</tbody></table></div></details>@endif
 </section>
 @endif
 @if($topic?->trashed())<section class="topic-panel"><p>专题已移入回收站。生成结果保持未采用，可从版本历史查看专题记录。</p><a class="text-blue-600" href="{{ $runData['topic_url'] }}">打开版本历史</a></section>@endif
 @if($run->status==='needs_adoption'&&$topic&&!$topic->trashed())
 <section class="topic-panel"><h2 class="text-lg font-semibold">对照 AI 建议</h2><p class="topic-help mt-2">@if($runData['field'])本次仅采用「{{ ['intro'=>'导语','summary'=>'摘要','tags'=>'标签','articles'=>'选文','seo'=>'搜索文案','faq'=>'常见问题','basic_info'=>'基本信息'][$runData['field']] }}」字段。@endif 选择需要采用的内容块，未勾选的人工字段保持原样。摘要事实需要对应选文；只采用选文时，现有摘要、问答和评分的引用也需要保留。依赖不完整会提示调整，保存和采用均保持未公开。</p>
 <form method="POST" action="{{ route('admin.topics.runs.action',['run'=>$run->id,'action'=>'adopt']) }}" class="mt-5 space-y-5">@csrf<input type="hidden" name="expected_version" value="{{ $topic->draft_version }}">
 @foreach(['intro'=>'导语','summary'=>'摘要','tags'=>'标签','articles'=>'选文','seo'=>'搜索文案','faq'=>'常见问题','basic_info'=>'基本信息'] as $field=>$label)
 @if((!$runData['field']||$runData['field']===$field)&&array_key_exists($field,$runData['suggestions']??[]))
 <div class="border border-gray-200 rounded-lg p-4"><label class="flex items-center gap-2 font-semibold"><input type="checkbox" name="fields[]" value="{{ $field }}" @checked(in_array($field,old('fields',[$runData['field']?:'intro']),true))>采用{{ $label }}</label><div class="grid gap-5 lg:grid-cols-2 mt-3"><div><h3 class="topic-help mb-2">当前内容</h3>@include('admin.topics._suggestion',['content'=>array_intersect_key($current,[$field=>true])])</div><div><h3 class="topic-help mb-2">建议内容</h3>@include('admin.topics._suggestion',['content'=>array_intersect_key($runData['suggestions']??[],[$field=>true])])</div></div></div>
 @endif
 @endforeach
 @error('fields')<p class="topic-error">{{ $message }}</p>@enderror @error('draft_version')<p class="topic-error">{{ $message }}</p>@enderror @error('articles')<p class="topic-error">{{ $message }}</p>@enderror
 <button class="topic-button topic-primary">采用到工作稿（所选内容）</button></form><form method="POST" action="{{ route('admin.topics.runs.action',['run'=>$run->id,'action'=>'ignore']) }}" class="mt-3">@csrf<button class="topic-button">忽略本次建议</button></form></section>
 @endif
</div>
<script>(()=>{const labels=@json($labels),phases={waiting:'等待队列',matching:'匹配本站公开文章',generating:'生成内容',saving:'保存草稿',publishing:'提交发布',finished:'本次处理结束'},root=document.querySelector('[data-topic-run]');let timer;async function poll(){try{const r=await fetch(root.dataset.statusUrl,{headers:{Accept:'application/json'}});if(!r.ok)throw Error();const d=await r.json();root.querySelector('[data-run-status]').textContent=labels[d.status]||d.status;root.querySelector('[data-run-phase]').textContent=phases[d.phase]||d.phase;root.querySelector('[data-run-error]').textContent=d.error||'';if(d.lease_expired!==@json($runData['lease_expired'])){location.reload();return;}if(['pending','running'].includes(d.status))timer=setTimeout(poll,3000);else if(@json($run->status)!==d.status)location.reload();}catch{root.querySelector('[data-run-error]').textContent='暂时无法获取状态，请刷新页面。';}}if(@json(in_array($run->status,['pending','running'])))timer=setTimeout(poll,3000);window.addEventListener('pagehide',()=>clearTimeout(timer));})();</script>
@if(session('topic_form_saved') && $topic)<script>try{sessionStorage.removeItem(@json('geoflow:topic:'.$site.':topic-'.$topic->id));}catch{}</script>@endif
@endsection