@extends('admin.layouts.app')
@section('topbar-title','专题设置')
@section('content')
@include('admin.topics._style')
<div class="topic-shell space-y-5"><div class="flex flex-wrap justify-between gap-3"><div><h1 class="text-2xl font-semibold">专题设置</h1><p class="topic-help mt-2">当前站点：{{ $sites[$site]??$site }}</p></div><a class="topic-button" href="{{ $returnTopic?route('admin.topics.edit',['topic'=>$returnTopic,'list_return'=>$listReturn??null]):($formToken?route('admin.topics.create',['site'=>$site,'form_token'=>$formToken,'list_return'=>$listReturn??null]):route('admin.topics.index',['site'=>$site])) }}">返回原页面</a></div><form method="GET" class="topic-panel flex flex-wrap items-end gap-3"><div class="min-w-48"><label>切换站点</label><select name="site">@foreach($sites as $key=>$name)<option value="{{ $key }}" @selected($site===$key)>{{ $name }}</option>@endforeach</select></div><button class="topic-button">查看设置</button></form>
 @if($namespaceConflicts)<section class="topic-panel space-y-3"><h2 class="font-semibold">现有文章地址需要迁移</h2><p class="topic-help">以下配置占用了 /topics：{{ implode('、',$namespaceConflicts) }}。专题草稿可以继续编辑。</p><a class="topic-button" href="{{ route('admin.site-settings.index') }}">打开网站地址设置</a></section>@endif
 @foreach($errors->all() as $error)<p class="topic-error" role="alert">{{ $error }}</p>@endforeach
 @if(!$canEdit)<p class="topic-panel topic-help">当前账号可查看专题设置。站点设置由超级管理员维护。</p>@endif
 <form method="POST" action="{{ route('admin.topics.settings.save') }}" data-topic-settings-form class="topic-panel space-y-5">@csrf<input type="hidden" name="site" value="{{ $site }}"><input type="hidden" name="topic" value="{{ $returnTopic }}"><input type="hidden" name="form_token" value="{{ $formToken }}"><input type="hidden" name="list_return" value="{{ $listReturn??'' }}"><fieldset @disabled(!$canEdit) class="space-y-4"><div><label>频道名称</label><input name="channel_name" maxlength="30" value="{{ old('channel_name',$settings['channel_name']??'专题') }}"><p class="topic-help mt-2">用于公开导航和专题列表标题。</p>@error('channel_name')<p class="topic-error">{{ $message }}</p>@enderror</div>@foreach(['enabled'=>'启用本站专题','home_enabled'=>'首页显示专题','navigation_enabled'=>'导航显示专题','require_review'=>'发布专题需要审核'] as $key=>$label)<label><input type="hidden" name="{{ $key }}" value="0"><input type="checkbox" name="{{ $key }}" value="1" @checked(old($key,$settings[$key]))> {{ $label }}</label>@endforeach<div class="grid gap-4 sm:grid-cols-2"><div><label>首页展示数量</label><input type="number" name="home_limit" min="1" max="12" value="{{ old('home_limit',$settings['home_limit']) }}"></div><div><label>默认模板</label><select name="default_template">@foreach(app(\App\Services\Topics\TopicTemplateCatalog::class)->options($site) as $key=>$label)<option value="{{ $key }}" @selected(old('default_template',$settings['default_template'])===$key)>{{ $label }}</option>@endforeach</select></div></div></fieldset>@if($canEdit)<button class="topic-button topic-primary">保存设置</button>@endif</form></div>
@if($canEdit && $rollbackState)<section class="topic-panel mt-5 space-y-3"><h2 class="font-semibold">专题模板兼容回退</h2><p class="topic-help">恢复升级前的设计，保留专题列表、详情和首页模块。专题内容与历史版本继续保存。</p><form method="POST" action="{{ route('admin.topics.settings.rollback') }}">@csrf<input type="hidden" name="site" value="{{ $site }}"><input type="hidden" name="binding_version" value="{{ $rollbackState['binding_version'] }}"><button class="topic-button">恢复上一版设计</button></form></section>@endif
<script src="{{ asset('admin/topic-editor.js') }}" defer></script>
@endsection